---
abstract: 'Moose config attribute loaded from file in home dir'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  English: 0
  Moose: 0
  Test::Exception: 0
  Test::More: 0
  rlib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Role
requires:
  Config::Any: 0
  File::HomeDir: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/robinsmidsrod/Config-Role.git
version: 0.0.1
